### ISSUE TITLE
MC suddenly turn blackout when playing

### ISSUE THREAD

**Issue by B-Wither** [hammertater/treechop#219]
When I play 1.19.2 forge, it suddenly black (more like grey) out and then server shut downs.
I saw log and it was written like this.

Error rendering overlay 'treechop:chopping_indicator'
java.lang.NullPointerException
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:710)
	at java.base/java.util.PriorityQueue.poll(PriorityQueue.java:585)
	at TRANSFORMER/treechop@0.18.4/ht.tuber.graph.FloodFillImpl.lambda$fill$2(FloodFillImpl.java:29)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
	at java.base/java.util.stream.Stream$2.tryAdvance(Stream.java:1539)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.common.chop.LazyTreeData.hasLeaves(LazyTreeData.java:99)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.api.AbstractTreeData.isAProperTree(AbstractTreeData.java:14)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.client.gui.screen.ChopIndicator.blockCanBeChopped(ChopIndicator.java:79)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.client.gui.screen.ChopIndicator.render(ChopIndicator.java:36)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.client.ForgeClient.lambda$onRegisterOverlays$0(ForgeClient.java:39)
	at TRANSFORMER/forge@43.2.8/net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/forge@43.2.8/net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.8/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.server.network.ServerGamePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.server.network.ServerGamePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.19.2 of loader 'TRANSFORMER' @150d6eaf)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundDisconnectPacket.m_5797_(ClientboundDisconnectPacket.java:7)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129517_(Connection.java:163)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.channelRead0(Connection.java:148)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.channelRead0(Connection.java:48)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by hammertater** [comment]
Thanks for sharing the log. Do you remember what you were looking at when the crash happened? A tree from a mod, a building with leaves blocks, etc.

**Comment by hammertater** [comment]
Yeah, it’s definitely caused by TreeChop - the log is very helpful! I’m just looking for any info on how to reproduce the crash so I can figure out why it’s happening and fix it. No worries though, I’ll look into it

**Comment by hammertater** [comment]
Could you share your mods list @B-Wither? Maybe upload your whole "latest.log" file, it's ok if it doesn't include the crash

**Comment by B-Wither** [comment]
[latest.log](https://github.com/hammertater/treechop/files/12444504/latest.log)
Here is.

**Comment by SidPrinceDesFlammes** [comment]
Hi, I ran into similar behavior in 1.20.1 when looking at an apotheosis tower (in a spruce forest, it has a special wooden skin)
Here is the log : 
[17:58:45] [Render thread/ERROR]: Error rendering overlay 'treechop:chopping_indicator'
java.lang.NullPointerException: null
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473) ~[?:?]
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:660) ~[?:?]
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:637) ~[?:?]
	at java.util.PriorityQueue.offer(PriorityQueue.java:330) ~[?:?]
	at java.util.PriorityQueue.add(PriorityQueue.java:311) ~[?:?]
	at ht.tuber.graph.FloodFillImpl.visitNode(FloodFillImpl.java:55) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at ht.tuber.graph.FloodFillImpl.lambda$fill$1(FloodFillImpl.java:26) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at ht.tuber.graph.FloodFillImpl.lambda$fill$2(FloodFillImpl.java:24) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540) ~[?:?]
	at java.util.stream.Stream$2.tryAdvance(Stream.java:1539) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at ht.treechop.common.chop.LazyTreeData.hasLeaves(LazyTreeData.java:99) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at ht.treechop.api.AbstractTreeData.isAProperTree(AbstractTreeData.java:14) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at ht.treechop.client.gui.screen.ChopIndicator.blockCanBeChopped(ChopIndicator.java:79) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at ht.treechop.client.gui.screen.ChopIndicator.render(ChopIndicator.java:36) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at ht.treechop.client.ForgeClient.lambda$onRegisterOverlays$0(ForgeClient.java:42) ~[TreeChop-1.20.1-forge-0.18.3.jar%23316!/:0.18.3]
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126) ~[forge-1.20.1-47.1.46-universal.jar%23325!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.1.46-universal.jar%23325!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:945) ~[client-1.20.1-20230612.114412-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23320!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.46.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.46.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.46.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.46.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by hammertater** [comment]
Hey, thanks a bunch! I’ll see if I can reproduce the error

**Comment by hammertater** [comment]
Couldn't really *fix* the error as of 0.18.5, but I think I've stopped it from causing crashes. Sorry for the wait y'all! Please reopen if anything bad still happens - I never actually managed to reproduce the crash.
