### ISSUE TITLE
Error from HT's TreeChop mod

### ISSUE THREAD

**Issue by Foxren** [hammertater/treechop#225]
Mod Loader: Forge
Game Version: 1.19.2
Mod Version: 0.18.4

Modlist: 
Advanced Netherite
Advancement Plaques
Advancement Tracker and Overview
Alex's Armoury
Appleskin
Architectury API
Art of Forging: A Tetra Addon
Artifacts
AttributeFix
AutoRegLib
Better Combat
Better FPS
Better Tridents
Bookshelf
Cataclysmic Combat
Catalogue
Citadel
Cloth Config API
Clumps
Comforts
Configured
Connectedness
Connectivity
Controlling
Create
Cupboard
Curios API
Durability Tooltip
Easy Anvils
Easy Magic
Enchantment Descriptions
Entity Culling
ESSENTIAL Mod
Explorify - Dungeons & Structures
Farmer's Delight
fix GPU memory leak
FPS Reducer
Game Menu Mod Option
Global Packs
Goblin Traders
GraveStone Mod
Guard Villagers
Handcrafted
HT's TreeChop
Iceberg
Illage and Spillage
Illagers Wear Armor
Immersive Aircraft
Immersive Armors
Immersive Engineering
Incendium
Jade
Just Enough Immersive Multiblocks
Just Enough Professions
Just Enough Resources
L_Ender's Cataclysm
LazyDataFixerUpper
Legendary Tooltips
Looot
Loot Beams
Loot Integrations
Lootr
Magnesium/Rubidium Dynamic Lights
Magnesium/Rubidium Extras
Majrusz Library
Majrusz's Progressive Difficulty
Mouse Tweaks
mutil
Numismatic Overhaul: Reforged
Oculus
playerAnimator
Polymorph
Prism
Puzzles Lib
Quark
Reforgium
REI Plugin Compatibilities
Repurposed Structures
Resourceful Lib
Roughly Enough Items
Rubidium
Rubidium Extra
Shutup Experimental Settings!
Skin Layers 3D
Sophisticated Backpacks
Sophisticated Core
Sound Physics Remastered
Spark
Structure Essentials
SuperMartijn642's Config Lib
Tetra
Tetra's Delight
Tetranomicon
Tetratic Combat
Textrue's Rubidium Options
The Lost Castle
Unusual End
Xaero's Minimap
Xaero's World Map
YUNG's API
YUNG's Better Desert Temples
YUNG's Better Dungeons
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Extras

Yes, I did type out my entire 109 mod list, so I hope this can contribute efficiently into solving this issue :)

![2023-09-10_16 10 34](https://github.com/hammertater/treechop/assets/107799358/9d88c73c-4496-4862-9850-d4c330f68547)

**Comment by hanleybrand** [comment]
Also saw this error - 

Debug log only says: 
```[Render thread/ERROR] [Jade/]: Caught unhandled exception : [ht.treechop.compat.Jade@26262d40] java.lang.NoSuchFieldError: component```

but jade logged this to JadeErrorOutput.txt:

```log

09/11/2023 - 22:02:27
ht.treechop.compat.Jade@26262d40
java.lang.NoSuchFieldError: component
	at TRANSFORMER/treechop@0.18.4/ht.treechop.compat.Jade.changeBlockName(Jade.java:70)
	at TRANSFORMER/treechop@0.18.4/ht.treechop.compat.Jade.appendTooltip(Jade.java:41)
	at TRANSFORMER/jade@8.9.0/snownee.jade.impl.BlockAccessorImpl._gatherComponents(BlockAccessorImpl.java:120)
	at TRANSFORMER/jade@8.9.0/snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:160)
	at TRANSFORMER/jade@8.9.0/snownee.jade.util.ClientPlatformProxy.onClientTick(ClientPlatformProxy.java:138)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.8/net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:830)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1852)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.8/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Comment by KitsuTheFloof** [comment]
Having the same issue

**Comment by hammertater** [comment]
Hey, sorry for the wait, thanks for reporting! Massive props for typing all that out! This will be fixed in the next update. Since it's the same issue as #200, I'm gonna close this and keep that one open.
