### ISSUE TITLE
TreeChop not functioning

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#254]
```
Minecraft v1.20.1-forge
TreeChop v.18.7
```

After updating to the new version today, treechop has not been functioning. The game loads fine but the mod doesn't load. From the logs, it is possibly an error with Jade. The previous version was working fine yesterday

<details closed>
<summary>Click for logs</summary>
<br>
<pre>
[13Jan2024 14:39:31.878] [Render thread/ERROR] [treechop/]: Something went wrong - please share this log file at https://github.com/hammertater/treechop/issues
ht.treechop.TreeChopException: Parameters: ClientLevel, MutableBlockPos{x=4, y=74, z=-8}, true, true
	at ht.treechop.compat.WailaUtil.addTreeInfoOrCrash(WailaUtil.java:96) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.compat.WailaUtil.addTreeInfo(WailaUtil.java:61) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.compat.Jade.appendTooltip(Jade.java:48) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at snownee.jade.impl.BlockAccessorClientHandler.gatherComponents(BlockAccessorClientHandler.java:87) ~[Jade-1.20.1-forge-11.7.1.jar%23623!/:11.7.1]
	at snownee.jade.impl.BlockAccessorClientHandler.gatherComponents(BlockAccessorClientHandler.java:25) ~[Jade-1.20.1-forge-11.7.1.jar%23623!/:11.7.1]
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:177) ~[Jade-1.20.1-forge-11.7.1.jar%23623!/:11.7.1]
	at snownee.jade.util.ClientProxy.onClientTick(ClientProxy.java:174) ~[Jade-1.20.1-forge-11.7.1.jar%23623!/:11.7.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:940) ~[forge-1.20.1-47.2.19-universal.jar%23787!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1875) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IllegalStateException: Duplicate key Block{minecraft:jungle_leaves} (attempted merging values ht.treechop.common.config.TreeLeavesBehavior$$Lambda$69696/0x0000000807b8b968@2371c5c5 and ht.treechop.common.config.TreeLeavesBehavior$$Lambda$69696/0x0000000807b8b968@2371c5c5)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at ht.treechop.common.config.ConfigHandler$Common.lambda$new$7(ConfigHandler.java:280) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.common.config.Lazy.get(Lazy.java:23) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.common.chop.ChopUtil.isBlockLeaves(ChopUtil.java:67) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.common.chop.ChopUtil.isBlockLeaves(ChopUtil.java:59) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.api.TreeDetectorBuilder.lambda$build$5(TreeDetectorBuilder.java:97) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.common.chop.LazyTreeData.check(LazyTreeData.java:86) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.common.chop.LazyTreeData.lambda$new$0(LazyTreeData.java:65) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at ht.tuber.graph.FloodFillImpl.lambda$fill$2(FloodFillImpl.java:23) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540) ~[?:?]
	at java.util.stream.Stream$2.tryAdvance(Stream.java:1539) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at ht.treechop.common.chop.LazyTreeData.hasLeaves(LazyTreeData.java:97) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.api.AbstractTreeData.isAProperTree(AbstractTreeData.java:14) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	at ht.treechop.compat.WailaUtil.addTreeInfoOrCrash(WailaUtil.java:77) ~[TreeChop-1.20.1-forge-0.18.7.jar%23747!/:0.18.7]
	... 30 more
</details>

**Comment by hammertater** [comment]
Ah, somehow the config's `treeDetection.leaves.blocks` has `jungle_leaves` listed twice (or a block tag that contains it). You may be able to fix it by fiddling with that list. I'll get the error fixed, thanks for reporting!

**Comment by hammertater** [comment]
Fixed in 0.18.7a

**Comment by WenXin20** [comment]
Thanks!
