### ISSUE TITLE
Tree Chop Exception

### ISSUE THREAD

**Issue by servicomcr** [hammertater/treechop#284]
[01:57:34] [Server thread/ERROR] [treechop/]: Something went wrong - please share this log file at https://github.com/hammertater/treechop/issues

ht.treechop.TreeChopException: Parameters: ServerPlayer['roshitocr'/38185, l='ServerLevel[raroland]', x=-1122.50, y=69.00, z=-607.79], ServerLevel[raroland], BlockPos{x=-1120, y=69, z=-608}, Block{minecraft:cherry_log}[axis=y], 1 iron_axe, net.minecraftforge.event.level.BlockEvent$BreakEvent@2db72ec0, 1, true, true

at ht.treechop.common.chop.ChopUtil.chop(ChopUtil.java:230) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.chop.ChopUtil.chop(ChopUtil.java:220) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.ForgeCommon.onBreakEvent(ForgeCommon.java:40) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.__ForgeCommon_onBreakEvent_BreakEvent.invoke(.dynamic) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading,pl:eventbus:B}

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}

at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:543) ~[forge-1.20.1-47.2.32-universal.jar%23256!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:A}

at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:229) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayerInteractionManagerMixin,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.ServerPlayerGameModeMixin,pl:mixin:A}

at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:218) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayerInteractionManagerMixin,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.ServerPlayerGameModeMixin,pl:mixin:A}

at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:188) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayerInteractionManagerMixin,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.ServerPlayerGameModeMixin,pl:mixin:A}

at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1020) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayNetworkHandlerMixin,pl:mixin:APP:apoli.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:inventorio.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:apugli.mixins.json:common.ServerPlayNetworkHandlerMixin,pl:mixin:APP:apugli.forge.mixins.json:common.ServerGamePacketListenerImplMixin,pl:mixin:A}

at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,re:classloading}

at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,re:classloading}

at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:classloading}

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:classloading}

at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}

at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,re:computing_frames,re:classloading}

at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at java.lang.Thread.run(Thread.java:1583) ~[?:?] {}

Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?] {}

at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?] {}

at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?] {}

at java.util.Objects.checkIndex(Objects.java:385) ~[?:?] {re:mixin}

at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}

at harmonised.pmmo.features.loot_modifiers.TreasureLootModifier.doApply(TreasureLootModifier.java:78) ~[pmmo-1.20.1-1.3.21.jar%23232!/:1.20.1-1.3.21] {re:classloading}

at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.2.32-universal.jar%23256!/:?] {re:classloading}

at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1186) ~[forge-1.20.1-47.2.32-universal.jar%23256!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:A}

at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at net.minecraft.world.level.storage.loot.LootTable.m_287195_(LootTable.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

at ht.treechop.common.block.ChoppedLogBlock.chop(ChoppedLogBlock.java:235) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.chop.Chop.apply(Chop.java:33) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.chop.ChopTreeResult.lambda$apply$0(ChopTreeResult.java:27) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at java.util.Vector.forEach(Vector.java:1359) ~[?:?] {}

at ht.treechop.common.chop.ChopTreeResult.apply(ChopTreeResult.java:27) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.chop.ChopUtil.chopUnsafe(ChopUtil.java:260) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

at ht.treechop.common.chop.ChopUtil.chop(ChopUtil.java:228) ~[TreeChop-1.20.1-forge-0.19.0.jar%23246!/:0.19.0] {re:classloading}

... 27 more

LOG Full [debug.log](https://github.com/user-attachments/files/16047191/debug.log)
[latest.log](https://github.com/user-attachments/files/16047192/latest.log)

**Comment by hammertater** [comment]
Thanks for reporting. Looks like a conflict with Project MMO, it could be on my side. I'll get it fixed.

**Comment by servicomcr** [comment]
Thanks for your prompt response, you haven't thought about making this mod for a plugin :) it would be great to have it on my other server

**Comment by hammertater** [comment]
Hey, it might be possible to make a plugin version, but none of the visual features would work. I'll think about it!
