### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by AzureMonument** [hammertater/treechop#92]
When chopping a tree with a tetra axe (do not know if it happens with normal axe), server crashes. 
Playing 1.18.1, forge version 39.0.36, TreeChop v0.15.1

Server thread/ERROR]: Encountered an unexpected exception
[16.01 21:47:58] [Server] java.lang.NoClassDefFoundErrorcom/ibm/icu/impl/Pair
[16.01 21:47:58] [Server] 	at ht.treechop.common.util.ChopUtil.getNumChops(ChopUtil.java:360) ~[TreeChop-1.18.1-0.15.1.jar%23156!:0.15.1]
[16.01 21:47:58] [Server] 	at ht.treechop.common.util.ChopUtil.chopTree(ChopUtil.java:228) ~[TreeChop-1.18.1-0.15.1.jar%23156!:0.15.1]
[16.01 21:47:58] [Server] 	at ht.treechop.common.util.ChopUtil.getChopResult(ChopUtil.java:167) ~[TreeChop-1.18.1-0.15.1.jar%23156!:0.15.1]
[16.01 21:47:58] [Server] 	at ht.treechop.common.util.ChopUtil.getChopResult(ChopUtil.java:161) ~[TreeChop-1.18.1-0.15.1.jar%23156!:0.15.1]
[16.01 21:47:58] [Server] 	at ht.treechop.common.Common.onBreakEvent(Common.java:84) ~[TreeChop-1.18.1-0.15.1.jar%23156!:0.15.1]
[16.01 21:47:58] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_47_Common_onBreakEvent_BreakEvent.invoke(.dynamic) ~[?:?]
[16.01 21:47:58] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
[16.01 21:47:58] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
[16.01 21:47:58] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
[16.01 21:47:58] [Server] 	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:541) ~[forge-1.18.1-39.0.36-universal.jar%23168!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:227) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23164!:?]
[16.01 21:47:58] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[16.01 21:47:58] [Server] Caused byjava.lang.ClassNotFoundException: com.ibm.icu.impl.Pair
[16.01 21:47:58] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
[16.01 21:47:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[16.01 21:47:58] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
[16.01 21:47:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[16.01 21:47:58] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
[16.01 21:47:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[16.01 21:47:58] [Server] 	... more

**Comment by hammertater** [comment]
Hey Azure, thanks for reporting. Sorry about that. I posted a new version (0.15.2 - https://www.curseforge.com/minecraft/mc-mods/treechop/files/3609307), it should fix the crash
